---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIp: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novabot-deployment
  labels:
    app: novabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novabot
  template:
    metadata:
      labels:
        app: novabot
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: roadkill
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim: mysql-pv-claim
